name: Build podman-dind-like

on:
  push:
    branches: 
      - 'release/**'
      - 'feature/**'
      - develop
    tags:
      - '*'
  pull_request:
    branches: 
      - main
      - 'release/**'
      - develop

env:
  GITHUB_DOCKER_USER: ${{ github.actor }}
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  build-and-push:
    runs-on: self-hosted
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
